### PR TITLE
Adding CTO Craft and CTO Craft Con 

### PR DESCRIPTION
**Pull request by andyskipper**
Added CTO Craft and CTO Craft Con

# Add a Slack Group

- [ ] Suggestion is not a duplicate
- [ ] Suggestion is placed in the proper country according the slack channel’s demographic or if it’s a general channel, it’s placed in the appropriate category
- [ ] Name and link are accurate
- [ ] Brief description of the channel is accurate and properly typed

# Remove a Slack Group

- [ ] Name of Slack group is present
- [ ] Reason for requesting removal is present

### CODE REVIEW

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Hi @andyskipper ! 

Thank you for your interest in our repository.

The links you provided are to a business site but this repository is accepting links for slack groups for people to join.

If you have a slack group you would like to add, please update your PR to include that. 👍

**Comment by andyskipper** [comment]
Hi Jessica! It is a free Slack community with just under 5,000 members - any CTO or senior engineering leader is welcome to join

Andy

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by andyskipper** [comment]
Thanks Jessica! 😊

**Pull request merged**
